### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by cwilby** [spatie/google-time-zone#10]
I started working on a fork that adds caching to this package before realizing the API requires a timestamp parameter.

Before I continue/exit, I'm hoping to confirm whether caching is possible or useful with this API?

**Comment by rubenvanassche** [comment]
Hi @cwilby,

Do you already have some code of this fork? I'm not entirely sure if I want to add caching to this package since it's a very simple package, actually it's only this file: https://github.com/spatie/google-time-zone/blob/master/src/GoogleTimeZone.php 

Caching isn't that simpele and probably would require a lot of code? And that's a lot of code we need to keep maintaining. So if that's the case I think a better solution would be to build a cache around the package and not inside it. 

But if the implementation is simple and doesn't require a lot of code then maybe it's a good fit!

What do you think?

**Comment by cwilby** [comment]
> I think a better solution would be to build a cache around the package and not inside it.

I agree - for the project I'm working on that inspired this fork I have added caching around the package which works for my purpose 👍 

That said, here's what I have: https://github.com/cwilby/google-time-zone/commit/ee2b055eec88a5e6d1eded77d22c9621d791b065

Some notes:

- Caching is disabled by default in an effort to avoid breaking changes.

-  Caching might not be useful considering the nature of the domain.  Timezones _in theory_ can change every second, and the timezone API requiring a timestamp parameter accounts for that.

-  I didn't get around to finishing the unit test, which in this case requires creating a Laravel application to mock `Cache::shouldReceive`.

**Comment by rubenvanassche** [comment]
Hi @cwilby, looks really cool but I think a caching solution is maybe a bit too far for this package. Also this package is built for Laravel and non-Laravel projects, this solution would only work with Laravel.

If you release your package, then let me know, I'll add a link in the readme to it so people who desire a package with caching can use your package.
